colors:
  dehumid_bg: "lightblue"
  dehumid_fg: "black"
  dehumid_text_fg: "black"
  dry_bg: "lightcoral"
  dry_fg: "black"
  dry_text_fg: "black"
  bg: "#f5f5f5"
  button_bg: "skyblue"  # 버튼 배경색
  button_fg: "white"     # 버튼 글자색
  
paddings:
  title:
    - 15
    - 5
  label_left:
    - 3
    - 
      - 10
      - 0
  label_right:
    - 3
    - 
      - 0
      - 10

shoes_pic_path: './pictures/running_shoe.png'